version: "3"

services:
  springboot-app:
    container_name: school-register-system
    image: springboot-app
    restart: always
    build: docker
    ports:
      - "8000:8080"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: rootroot#123

  mysqldb:
    container_name: springapi
    image: springapi
    volumes:
      - C:\ProgramData\MySQL\MySQL Server 8.1\Data
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: school_registration_system
      MYSQL_ROOT_PASSWORD: rootroot#123
